#!/usr/bin/python3.11

import argparse
import logging
import re
import tomllib
from pathlib import Path
from packaging.markers import Marker

RPM_NAME_MAP = {
    # Mapping from PyPI name to RPM package name suffix (e.g., "authlib" -> "Authlib")
    "authlib": "Authlib",
    "markupsafe": "MarkupSafe",
    "pyyaml": "PyYAML",
    "werkzeug": "Werkzeug",
}

RPM_SPECIAL_REQUIRES_MAP = {
    # Special cases for packages that don't follow the %{python_module ...} macro convention
    "python-dotenv": "%{pythons}-python-dotenv",
    "python-multipart": "%{pythons}-python-multipart",
}

class SpecUpdater:
    """A class to update RPM spec files from a uv.lock file."""

    def __init__(self, spec_file_path: Path, project_root: Path):
        self.spec_file_path = spec_file_path
        self.project_root = project_root
        self.uv_lock_path = project_root / "uv.lock"
        self.pyproject_path = project_root / "pyproject.toml"
        self.new_start_marker = "# List of python dependencies from uv.lock generated by pydeps.py"
        self.old_start_marker = "# List of python dependencies from pyproject.toml generated by pydeps.py"
        self.end_marker = "# End"

    def _get_project_name_from_pyproject(self) -> str | None:
        """Reads the project name from pyproject.toml."""
        try:
            with open(str(self.pyproject_path), "rb") as f:
                pyproject_data = tomllib.load(f)
            project_name = pyproject_data.get('project', {}).get('name')
            if not project_name:
                logging.error("Could not find project name in %s", self.pyproject_path)
                return None
            return project_name
        except FileNotFoundError:
            logging.error("pyproject.toml not found at %s", self.pyproject_path)
            return None
        except tomllib.TOMLParseError as e:
            logging.error("Error parsing pyproject.toml at %s: %s", self.pyproject_path, e)
            return None

    def _generate_dependency_lines(self) -> list[str] | None:
        """Generates 'Requires' lines by recursively resolving dependencies from uv.lock."""
        with open(self.uv_lock_path, "rb") as f:
            data = tomllib.load(f)

        packages_by_name = {}
        for pkg in data.get('package', []):
            packages_by_name.setdefault(pkg['name'], []).append(pkg)

        project_name = self._get_project_name_from_pyproject()
        if not project_name:
            return None

        main_project_list = packages_by_name.get(project_name)
        main_project = main_project_list[0] if main_project_list else None
        if not main_project:
            logging.error("'%s' package not found in %s", project_name, self.uv_lock_path)
            return None

        py_version_match = re.search(r'(\d+\.\d+)', data.get("requires-python", ""))
        if not py_version_match:
            logging.warning("Could not determine Python version from 'requires-python' in uv.lock. Defaulting to 3.11.")
            py_version = "3.11"
        else:
            py_version = py_version_match.group(1)

        marker_env = {
            "sys_platform": "linux",
            "python_version": py_version,
            "implementation_name": "cpython",
        }

        all_deps = set()
        worklist = list(main_project.get('dependencies', []))
        processed = {dep['name'] for dep in worklist}

        while worklist:
            dep = worklist.pop(0)
            dep_name = dep['name']

            if 'marker' in dep and not Marker(dep['marker']).evaluate(environment=marker_env):
                logging.debug("Skipping '%s' due to marker: %s", dep_name, dep['marker'])
                continue

            dep_details_list = packages_by_name.get(dep_name)
            dep_details = dep_details_list[0] if dep_details_list else None
            if not dep_details:
                logging.warning("Dependency '%s' not found in uv.lock. Skipping.", dep_name)
                continue

            all_deps.add(dep_name)
            for sub_dep in dep_details.get('dependencies', []):
                if sub_dep['name'] not in processed:
                    processed.add(sub_dep['name'])
                    worklist.append(sub_dep)

        dep_lines = []
        for pkg_name in sorted(list(all_deps)):
            dep_pkg = packages_by_name[pkg_name][0]
            version = dep_pkg.get('version')

            if pkg_name in RPM_SPECIAL_REQUIRES_MAP:
                dep_str = f"{RPM_SPECIAL_REQUIRES_MAP[pkg_name]} = {version}" if version else RPM_SPECIAL_REQUIRES_MAP[pkg_name]
                dep_lines.append(f"Requires:       {dep_str}")
            else:
                rpm_name = RPM_NAME_MAP.get(pkg_name, pkg_name)
                dep_str = f"{rpm_name} = {version}" if version else rpm_name
                dep_lines.append(f"Requires:       %{{python_module {dep_str}}}")

        return dep_lines

    def run(self) -> bool:
        """Executes the entire update process."""
        logging.info("Generating dependencies from %s...", self.uv_lock_path)
        new_deps = self._generate_dependency_lines()

        if new_deps is None:
            logging.error("Failed to generate dependencies. Exiting.")
            return False

        try:
            with open(self.spec_file_path) as f:
                lines = f.readlines()
        except FileNotFoundError:
            logging.error("Spec file not found at %s", self.spec_file_path)
            return False

        start_index, end_index = -1, -1
        for i, line in enumerate(lines):
            if self.new_start_marker in line or self.old_start_marker in line:
                start_index = i
            if self.end_marker in line and start_index != -1:
                end_index = i
                break

        if start_index == -1 or end_index == -1:
            logging.error("Could not find dependency markers in %s", self.spec_file_path)
            return False

        new_content = lines[:start_index] + [self.new_start_marker + '\n'] + [d + '\n' for d in new_deps] + lines[end_index:]

        with open(self.spec_file_path, 'w') as f:
            f.writelines(new_content)

        logging.info("Successfully updated %s with %d dependencies.", self.spec_file_path, len(new_deps))
        return True

def main():
    """Main function to update the spec file with dependencies."""
    parser = argparse.ArgumentParser(description="Update RPM spec file dependencies from uv.lock.")
    parser.add_argument("spec_file", help="Path to the .spec file to update.")
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose (DEBUG) logging."
    )
    args = parser.parse_args()

    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(level=log_level, format="%(levelname)s: %(message)s")

    script_dir = Path(__file__).parent.resolve()
    project_root = script_dir.parent
    spec_file_path = Path(args.spec_file).resolve()

    updater = SpecUpdater(spec_file_path, project_root)
    if not updater.run():
        exit(1)

if __name__ == "__main__":
    main()
